name: portfolio_website
description: A professional portfolio website built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  url_launcher: ^6.2.4
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.9
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.7.0
  visibility_detector: ^0.4.0+2
  responsive_framework: ^1.5.1
  flutter_screenutil: ^5.9.3
  animate_do: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/skills/
    - assets/icons/Projects_icons/
